### ISSUE TITLE
Changing L2&L1 tags on explore pages into the network name tag

### ISSUE THREAD

**Issue by zkDavison** [zkLinkProtocol/block-explorer#57]
#### 📝 Description

The current explore is fork from zkSync. However, as Nova has different architecture, e.g., L3, multi-chain deployment, the L2&L1 tags on Explore pages should be switched to the network names (e.g. Nova, Ethereum, zkSync), which help users the know where a transaction happened.

Pages need to be fixed include:
Batch transactions in "from" & "to" field in: 
https://explorer.zklink.io/block/43143
https://explorer.zklink.io/batch/1204
https://explorer.zklink.io/transactions/
https://explorer.zklink.io/tx/0xbf4be581d202e344ca04912791ae3f70a7c3044866af11148142663325166e41

**Comment by haymond-ZK** [comment]
The relevant interfaces need to add the 'networkkey' field.

**Comment by Evan-zkLinkLabs** [comment]
https://explorer.zklink.io/tx/0x2ece61b09a7ad7c83904509f576d70c6941df012060a74fe410913d1d0ac1b22

**Comment by Evan-zkLinkLabs** [comment]
Explorer Display Issue: Wrong Dest Chain when user withdraw

**Comment by Troyyyy-whihor** [comment]
This issue was temporarily fixed by the front-end, but the backend engineer will continue to investigate the root problems.
